# Generated by Django 2.2.3 on 2019-08-10 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190724_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Songname', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('song_src', models.TextField()),
                ('introduce', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('upddatedate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pubdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Voice')),
            ],
        ),
    ]
