# Generated by Django 2.2.3 on 2019-08-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190810_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='like',
        ),
    ]
