# Generated by Django 2.2.3 on 2019-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_voice_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pubdate']},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'ordering': ['-updatedate']},
        ),
        migrations.RenameField(
            model_name='voice',
            old_name='upddatedate',
            new_name='updatedate',
        ),
        migrations.AddField(
            model_name='voice',
            name='like',
            field=models.ManyToManyField(to='home.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
