# Generated by Django 2.2.3 on 2019-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190810_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='like',
            field=models.ManyToManyField(blank=True, to='home.User'),
        ),
    ]
