# Generated by Django 2.2.3 on 2019-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190810_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='File',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
