# Generated by Django 2.2.3 on 2019-09-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_mysong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysong',
            name='Song',
        ),
        migrations.AddField(
            model_name='mysong',
            name='Song',
            field=models.ManyToManyField(to='home.Voice'),
        ),
        migrations.RemoveField(
            model_name='mysong',
            name='User',
        ),
        migrations.AddField(
            model_name='mysong',
            name='User',
            field=models.ManyToManyField(to='home.User'),
        ),
    ]
