# Generated by Django 2.2.3 on 2019-09-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190905_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySong',
        ),
    ]
