# Generated by Django 2.2.3 on 2019-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_mysong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='id',
        ),
        migrations.AddField(
            model_name='voice',
            name='SongID',
            field=models.AutoField(default='n', primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
